# Generated by Django 2.2.5 on 2019-09-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='estoque_minimo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='importado',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ncm',
        ),
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
